---
name: Matrix Output
description: >-
  Collect outputs from each matrix job.
inputs:
  yaml:
    description: >-
      A string representing YAML data. Typically, a simple dictionary of key/value pairs.
    type: string
    required: true
outputs:
  json:
    description: >-
      A string representing a JSON list of dictionaries. Each dictionary in the list
      contains the output for a single job from the job matrix. The order of this list
      corresponds to the job index (i.e. `strategy.job-index`).
    value: ${{ steps.merge.outputs.json }}
runs:
  using: composite
  steps:
    - name: Generate job output
      shell: bash
      run: yq -o=json <<<"${input_yaml:?}" >job-output.json
      env:
        input_yaml: ${{ inputs.yaml }}
    - name: Upload job output
      uses: actions/upload-artifact@v4
      with:
        name: matrix-output-${{ github.job }}-${{ strategy.job-index }}
        path: job-output.json
        if-no-files-found: error
    - name: Determine available matrix job outputs
      id: job-output
      shell: bash
      run: |
        # https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-workflow-run-artifacts
        artifacts="$(gh api -X GET "/repos/{owner}/{repo}/actions/runs/${run_id:?}/artifacts" --jq '.artifacts')"
        num_job_uploads="$(jq --arg prefix "${prefix:?}" 'map(select(.name | startswith($prefix))) | length' <<<"$artifacts")"
        echo "Uploaded ${num_job_uploads}/${{ strategy.job-total }}" >&2
        echo "num=${num_job_uploads:?}" | tee -a "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ github.token }}
        prefix: matrix-output-${{ github.job }}-
        run_id: ${{ github.run_id }}
    - name: Download job matrix outputs
      uses: actions/download-artifact@v4
      if: ${{ steps.job-output.outputs.num == strategy.job-total }}
      with:
        pattern: matrix-output-${{ github.job }}-*
        path: matrix-output
        merge-multiple: false
    - name: Merge job matrix output
      id: merge
      if: ${{ steps.job-output.outputs.num == strategy.job-total }}
      shell: bash
      run: |
        # Specify our multiline output using GH action flavored heredocs
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        {
            echo "json<<EOF"
            jq -s '.' matrix-output/*/*.json
            echo "EOF"
        } | tee -a "$GITHUB_OUTPUT"
