---
name: Matrix Output
description: >-
  Collect outputs from each matrix job.
inputs:
  yaml:
    description: >-
      A string representing YAML data. Typically, a simple dictionary of key/value pairs.
    type: string
    required: true
outputs:
  json:
    description: >-
      A string representing a JSON list of dictionaries. Each dictionary in the list
      contains the output for a single job from the job matrix. The order of this list
      corresponds to the job index (i.e. `strategy.job-index`).
    value: ${{ steps.merge.outputs.json }}
runs:
  using: composite
  steps:
    - name: Generate job output
      shell: bash
      run: yq -o=json <<<"${input_yaml:?}" >job-output.json
      env:
        input_yaml: ${{ inputs.yaml }}
    - uses: beacon-biosignals/matrix-output/job-context@b2b42fddbb864ed0787bd2d497a9dfd11ad12c47
      id: job
      with:
        path: ${{ github.action_path }}/repo
    - name: Upload job output
      uses: actions/upload-artifact@v4
      with:
        name: matrix-output-${{ github.job }}-${{ strategy.job-index }}-${{ steps.job.outputs.job-id }}
        path: job-output.json
        if-no-files-found: error
    - name: Download job matrix outputs
      uses: actions/download-artifact@v4
      with:
        pattern: matrix-output-${{ github.job }}-*
        path: matrix-output
        merge-multiple: false
    - name: Merge job matrix output
      id: merge
      shell: bash
      run: |
        ls matrix-output
        # Specify our multiline output using GH action flavored heredocs
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        {
            echo "json<<EOF"
            jq -s '.' matrix-output/*/*.json
            echo "EOF"
        } | tee -a "$GITHUB_OUTPUT"
